# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"
apply = ["defer"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]
hooks.post = '''
zsh-defer autoload -Uz compinit
zsh-defer compinit
zsh-defer autoload bashcompinit
zsh-defer bashcompinit
'''

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
apply = ["source"]
hooks.post = "source ~/.config/zsh/p10k.zsh"

[plugins.on-demand-completion]
local = "~/.config/zsh/plugins/on-demand-completion"
apply = ["source"]

[plugins.pyrunbox]
local = "~/.config/zsh/plugins/pyrunbox"
apply = ["source"]

# lazy

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.docker-completion]
inline = "zsh-defer on_demand_completion 'docker'"

[plugins.mise-completion]
inline = "zsh-defer on_demand_completion 'mise'"

[plugins.talhelper-completion]
inline = "zsh-defer on_demand_completion 'talhelper'"

[plugins.gh-completion]
inline = "zsh-defer on_demand_completion 'gh' 'gh completion -s zsh'"

[plugins.op-completion]
inline = "zsh-defer on_demand_completion 'op'"

[plugins.kubectl-completion]
inline = "zsh-defer on_demand_completion 'kubectl'"

[plugins.talosctl-completion]
inline = "zsh-defer on_demand_completion 'talosctl'"

[plugins.aws-completion]
inline = "zsh-defer on_demand_completion 'aws' 'complete -C aws_completer aws' false"

[plugins.argocd-completion]
inline = "zsh-defer on_demand_completion 'argocd' 'argocd completion zsh'"
